[functions]
  external_node_modules = ["express"]
  node_bundler="esbuild"
[build]
  functions="functions"
[dev]
  publish="dist"
[[redirect]]
    from="/*"
    to="/.netlify/functions/api/"
    status=200
